const wallet='TRTrSXwbrtELFr6ivpPUxMaoNGdYUNoPma';
const p=new URLSearchParams(location.search);
const plan=(p.get('plan')||'STARTER').toUpperCase();
const amount=p.get('amount')||'200';
const plans={STARTER:['STARTER','10 Days • 30 Signals Daily • AI Signal Analysis • Chart Screenshot Upload'],PRO:['PRO','1 Month • 100 Signals Daily • AI Signal Analysis • Chart Screenshot Upload'],ELITE:['ELITE','Permanent • Unlimited Signals Daily • AI Signal Analysis • Chart Screenshot Upload']};
const x=plans[plan]||plans.STARTER;
document.getElementById('plan').textContent=x[0];
document.getElementById('price').textContent='$'+amount.replace('$','');
document.getElementById('details').textContent=x[1];
new QRCode(document.getElementById('qr'),{text:wallet,width:196,height:196});
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(wallet);document.getElementById('msg').textContent='Address copied.'}catch(e){document.getElementById('msg').textContent='Long-press the address to copy.'}};
document.getElementById('paid').onclick=()=>document.getElementById('status').textContent='Submitted for verification. Automatic activation requires the payment backend/webhook.';
window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand();